# To use:
#
#   $ micromamba create -f environment.yml  # `micromamba` works too for this command
#   $ micromamba activate readcon_dev
#
name: readcon_dev
channels:
  - conda-forge
dependencies:
  - compilers
  - meson
  - ninja
  - cmake
  - pkg-config
  # Backports away from C++20
  - range-v3
  - fmt==9.1.0
  # Tests
  - gtest
  - gmock
  # Optional
  - arrow-cpp
